######################################################################
# Automatically generated by qmake (3.0) Thu Mar 26 14:45:38 2015
######################################################################

TEMPLATE = app
TARGET = sp
INCLUDEPATH += .
CONFIG += c++11

# Input
SOURCES += main.cpp
